### ISSUE TITLE
Again running into a problem in the FSI

### ISSUE THREAD

**Issue by halcwb** [Zaid-Ajaj/DustyTables#16]
**Describe the bug**
I am getting a bit desperate and frustrated.

Completely out of the blue I am no longer able to use the SqlDataClient in a script file getting the below error. I had previously problems to get things up and running, but managed it with setting the reference to the runtimes/win SqlDataClient dll and 

````
AppContext.SetSwitch("Switch.Microsoft.Data.SqlClient.UseManagedNetworkingOnWindows", true)
````

Then suddenly out of the blue I get the below error:

```
Exception message:
Stack trace:
    System.MissingMethodException: Method not found: 'System.String System.String.TrimStart()'.
   at Microsoft.Data.LocalDBAPI.GetLocalDbInstanceNameFromServerName(String serverName)
   at Microsoft.Data.SqlClient.SqlConnectionString..ctor(String connectionString) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnectionString.cs:line 286
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnectionFactory.cs:line 140
   at Microsoft.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions) in /_/src/Microsoft.Data.SqlClient/netcore/src/Common/src/Microsoft/Data/ProviderBase/DbConnectionFactory.cs:line 230
   at Microsoft.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnectionHelper.cs:line 71
   at Microsoft.Data.SqlClient.SqlConnection.set_ConnectionString(String value) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs:line 517
   at DustyTables.SqlModule.getConnection(SqlProps props)
   at DustyTables.SqlModule.execute[t](FSharpFunc`2 read, SqlProps props)
      {Data = dict [];
       HResult = -2146233069;
       HelpLink = null;
       InnerException = null;
       Message = "Method not found: 'System.String System.String.TrimStart()'.";
       Source = "Microsoft.Data.SqlClient";
       StackTrace = "   at Microsoft.Data.LocalDBAPI.GetLocalDbInstanceNameFromServerName(String serverName)
   at Microsoft.Data.SqlClient.SqlConnectionString..ctor(String connectionString) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnectionString.cs:line 286
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnectionFactory.cs:line 140
   at Microsoft.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions) in /_/src/Microsoft.Data.SqlClient/netcore/src/Common/src/Microsoft/Data/ProviderBase/DbConnectionFactory.cs:line 230
   at Microsoft.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnectionHelper.cs:line 71
   at Microsoft.Data.SqlClient.SqlConnection.set_ConnectionString(String value) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs:line 517
   at DustyTables.SqlModule.getConnection(SqlProps props)
   at DustyTables.SqlModule.execute[t](FSharpFunc`2 read, SqlProps props)";
       TargetSite = System.String GetLocalDbInstanceNameFromServerName(System.String);}
```

**To Reproduce**
See my repository, I can also demonstrate this life to you @Zaid-Ajaj 

**Expected behavior**

**Comment by Zaid-Ajaj** [comment]
Hi Casper, this looks a nasty resolution error from FSI, if it can't find `.TrimStart()` from `System.String` then something is really off. To be honest, I don't know why this happens. It is usually a combination of
 - Which SDK are you running (net5 or less?)
 - FSI running in preview or not 
 - FSI resolving FSharp.Core on its own or are you using paket to resolve the dependencies?

I can look into it sometime soon, it is really hard for me to troubleshoot this since I almost never use fsharp scripts (primarily because of these resolution issues)

**Comment by halcwb** [comment]
@Zaid-Ajaj. Thanks for the quick reply. The problem is using netcore. When I switch to .net framework, everything works.

As to using the FSI. This I really would like to discuss with you. One of the prime reasons I like F# so much is that I can write literally whole applications in a FSX file. That makes developing a real pleasure, the REPL principle. The problem is, as you mention, that dependency resolution is a bit of a PITA. 

Do you feel this is something we could discuss higher up in the F# community?

**Comment by Zaid-Ajaj** [comment]
Absolutely, I think if you create a small repro with a fax file and open an issue dotnet/fsharp, it should be picked up soon. You can also try the #compiler channel on slack where people hang out that potentially know how to solve this

**Comment by halcwb** [comment]
@Zaid-Ajaj I am in the process of writing things down in a blog and trying to come up with minimal scenario's. Takes some time thought, keep you posted. Thanks.
